version: '3.5'
services:
  postgres-server:
    env_file: .env
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  web:
    build: .
    image: api-manager-school:1.0.0
    env_file: .env
    environment:
      - DATABASE_HOSTNAME_DEV=${DATABASE_HOST}
      - DATABASE_USERNAME_DEV=${DATABASE_USERNAME}
      - DATABASE_PASSWORD_DEV=${DATABASE_PASSWORD}
      - DATABASE_HOSTNAME_TEST=${DATABASE_HOST}
      - DATABASE_USERNAME_TEST=${DATABASE_USERNAME}
      - DATABASE_PASSWORD_TEST=${DATABASE_PASSWORD}
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres-server
    links:
      - postgres-server